# Generated by Django 5.0.2 on 2024-05-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(upload_to='covers/')),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
