# Generated by Django 5.0.2 on 2024-05-19 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='cast',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='trailer',
            name='full_details',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailer',
            name='poster_image',
            field=models.ImageField(default='posters/default_poster.jpg', upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trailer',
            name='youtube_trailer_link',
            field=models.URLField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
        ),
    ]
