# Generated by Django 5.0.2 on 2024-05-21 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_trailer_cast_trailer_full_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movieapp.trailer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.user')),
            ],
        ),
    ]
