# Generated by Django 5.0.2 on 2024-05-21 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='trailer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.category'),
        ),
    ]
