# Generated by Django 5.0.2 on 2024-05-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0009_remove_trailer_email_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
